name: Guides
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- vendor

theme: jekyll-theme-guides-mbland
permalink: pretty
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Mike Bland
  url: https://mike-bland.com/

navigation:
- text: Guides Template
  url: /guides-template

# google_analytics_ua:

repos:
- name: Guides
  description: Main repository
  url: https://github.com/mbland/guides
- name: jekyll-theme-guides-mbland
  description: Theme repository
  url: https://github.com/mbland/jekyll-theme-guides-mbland

back_link:
  url: "https://mike-bland.com/"
  text: "Back to Mike Bland's site"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

jekyll_pages_api_search:
  skip_index: true
